Review
KsuyVas/slozhno-sosredotochitsya pull request #1
Opened 2023-12-03 19:07 UTC by KsuyVas

Здравствуйте. Отправляю на ревью проект "Сложно сосредоточиться"

2023-12-03 21:35 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа. _Пожалуйста, не торопитесь, и после исправления проверяйте исправление всех критических комментариев и соответствие макету на всех брейкпоинтах._


_Что понравилось:_


- работают темы и автотемы
- Правильное форматирование
- Корректная структура HTML
- Валидный код
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Хорошо адаптирована вся страница
- Похоже на макет на брейк-поинтах


_Что необходимо исправить:_

- Все комментарии, кроме комментариев «Можно лучше» и «Отлично»

- https://disk.yandex.ru/i/oK6RUhxUxlj3fQ
  - шрифт нужно задавать через переменную
  - Название шрифта, которое содержит пробелы нужно всегда брать в кавычки, или браузер может не понять это значение
  - **Тип альтернативного браузерного шрифта для каждого св-ва font-family используйте monospace** Нужно указать альтернативный шрифт (тип шрифта для выбора шрифта браузера такого же типа по-умолчанию) для каждого значения font-family в проекте, кроме файла подключения шрифтов, где это св-во задаёт только название подключаемого шрифта.   https://doka.guide/css/font-family/#znacheniya




- https://disk.yandex.ru/i/3CehpbqJD1jhPA у этих заголовков(именно у пяти, не включая сверху) не должно быть жирного шрифта на всех ширинах экрана

- https://disk.yandex.ru/i/0HI7GpbkR_fwWw 
    - у класса активной кнопки должна быть всегда обводка кнопки цвета из макета в соответствии с темой

- **При исправлении для одной из тем (светлой/тёмной) обязательно проверяйте, чтобы при такой же автотеме (светлой/тёмной) было соответствующее исправление.** Это напоминалка, а не конкретное исправление.



- при светлых темах(проверяйте и на авто-светлой и светлой теме) при любой ширине экрана:
  - https://disk.yandex.ru/i/GWID_LISmBvCmQ // https://disk.yandex.ru/i/1yUOmZzFdE89lA не те цвета


-  до 768 px включительно и от 1024px включительно ширины экрана при светлой теме **и светлой автотеме** цвет тени заголовков **footer и header**  должен быть **разный**. При большей ширине более яркий цвет из макета 
    -   https://disk.yandex.ru/i/q21Yvs8FJ4g9-g  
    -   https://disk.yandex.ru/i/NzmqaFqGVZiE_Q



- при тёмных темах(проверяйте и на авто-тёмной и тёмной теме) при любой ширине экрана:
  - https://disk.yandex.ru/i/WFTg1KVWkdqUlQ при обычной тёмной теме при выборе авто-светлой пропадает элемент rec


- при навигации по странице с клавиатуры клавишами Tab/shift+tab по интерактивным элементам нужно исправить для состояния видимого фокуса при любой ширине экрана:
  -  https://disk.yandex.ru/i/WhHZ3rTF2m0XwA некорректный цвет подчёркивания при светлых темах

- при состоянии ховера на интерактивных элементах при любой ширине экрана нужно исправить:
  - https://disk.yandex.ru/i/rH06oaVPVjF-hQ некорректный цвет обводки при тёмных темах


- Для корректного отображения страницы между брейкпоинтами необходимо интервалы медиа правил. Для страницы макета с шириной 375px можно использовать отображение на веб-странице хоть до 767px ширины c адаптацией(резиновой версткой), соответственно для страницы макета 768px хоть до 1023px ширины веб-страницы. При таких интервалах стили не будут отображаться некорректно и не будет слишком маленьких элементов на странице. Примеры из текущей версии:
    - https://disk.yandex.ru/i/YQfuZjISiUP2xw элементы липнут друг к другу
    - https://disk.yandex.ru/i/Z_2vZU-34pzVMw ширина столбика текста слишком узкая, почти до следующего брейкопинта из макета можно смело использовать схожий вид с адаптацией, как при предыдущем брейкпоинте макета
    - https://disk.yandex.ru/i/-W5TGfhtkx7tZw очень маленькие картинки в галлерее после прохождения брейкпоинта. Самый простой вариант это увеличить диапазоны ширин для предыдущих брейкпоинтов чтобы в одну колонку шло пускай хоть до 767px, а другой вид секции уже от 768px и больше.  Тогда картинки не будут сразу очень маленькие(хотя бы от 230px ширины элемента) после прохождения нового брейкпоинта и всё будет красиво


 - **при ширине экрана более 1440px  всё должно выглядеть так же как при 1440px, только с разным расстоянием от краёв экрана**. Максимальная ширина контента в стилях изначально задана как 1440px, её не нужно менять. При ширине страницы более 1440 должны прибавляться только края:
     -  https://disk.yandex.ru/i/rKJHk4hJ059RSg // https://disk.yandex.ru/i/-3reIP0mzeujdg   вид страницы от 1024px до 1440рх должен быть как при 1024, но с резиновой вёрсткой, максимальная ширина контента должна быть 1440рх


- Для ширины экрана 1024px _не совпадает с макетом_ :
  -   https://disk.yandex.ru/i/n4qfY7aVh6NDwA размер шрифта в хедере и футере

- Для ширины экрана 768px _не совпадает с макетом_ : 
  -  https://disk.yandex.ru/i/GSSThKBxdtZF0w размер шрифта в хедере и футере

- При ширине экрана 375px  _не совпадает с макетом_:
  -   https://disk.yandex.ru/i/paRPsdguAp9MBw размер шрифта в хедере(и выравнивание h1) и футере


- https://disk.yandex.ru/i/hFpnhTfGIL1qLQ примерно от 376px до 460px ширины экрана страница прокручивается по горизонтали
   - Для некоторых элементов нужно поменять стили и/или диапазон ширин брейкпоинтов в медиаправилах. Для устранения горизонтального скролла часто применяют подобный подход: можно прямо в Dev Tools(или через IDE) по одной скрывать секции и смотреть когда он пропадает, и потом добавляют по одной устраняя скролл на всех разрешениях. Плюс можно добавить например красный бордер(или аутлайн) для всех элементов(селектор для всех элементов `*`) и посмотреть что вылезает. А так же можно еще раз просмотреть уроки с платформы, где тоже есть много полезных советов. 
    - _Скролл нужно убирать без св-ва overflow, нужно подправить верстку на тех интервалах ширина экрана где это необходимо_




_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- CSS-правила в коде желательно распологать в примерном соответствии с позицией элементов в DOM.

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome
- Можно использовать `transition` для более плавных переходов Hover эффектов. Это улучшает визуальное восприятия. Для работы `transition` сразу на наведение и на снятие нужно указать его к самому селектору, а не к hover этого селектора
- Можно использовать удобное сокращение  [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background)
- Для единообразного форматирования документов в VSCode лучше положить файл `.editorconfig` в корневой каталог
- А так же можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`



**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +      <p class="text-cards">Или даже пробегитесь. Лучше найти парк или лес: один эксперимент показал, что созерцание
- слово "показал" так же должно быть ссылкой, как выше на странице

- Нужно заполнить адрес ссылки из макета и добавить атрибут `target="_blank"` для открытия ссылки в новой вкладке

2023-12-03 21:35 UTC, Avaakum commented on styles/style.css
> +@media (375px < width <=768px) {
---

**Отлично:**

Используется современный синтаксис для правил медиа

2023-12-03 21:35 UTC, Avaakum commented on styles/light.css
> +@media (prefers-color-scheme: light) {
---

**Отлично:**

Мы описываем цветовые схемы в теге meta в  html.  Мы изначально выбираем одну тему как основную(тёмную или светлую), и страница должна корректно отображаться при выборе авто-темы с той, которой мы задавали как основную. 
  -   Например, если мы решили использовать по-умолчанию тему и автотему тёмную(эту тему мы как раз указываем в html в метатеге первой), то в файле variables задаём все переменные  в под тёмную тему для селектора root, а фон для страницы и отображение  rec и если есть другие отличия добавляем в style.css. Далее в файле тёмной темы для класса тёмной темы нужно копировать все эти стили: значения переменных, отображение rec и фон страницы.  При включении светлой темы применяются стили из класса светлой темы, которые должны быть заданы в файле  light.css. А при включении авто-темы "светлой" уже будет будет использовано медиа правило ` prefers-color-scheme: light ` из этого же файла, в котором дублируются стили от светлой темы, только уже не для класса, а для селектора :root, плюс остальные моменты, как показ rec и прочее

2023-12-03 21:35 UTC, Avaakum commented on styles/light.css
> +:root.theme-light {
Лишний селектор, некорректный селектор, такого элемента нет

2023-12-03 21:35 UTC, Avaakum commented on styles/dark.css
> +:root.theme-dark {
Лишний селектор, некорректный селектор, такого элемента нет

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <meta name="color-scheme" content="dark light">
---

**Отлично:**

Цветовые схемы описаны в тэге

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <link rel="stylesheet" href="./styles/globals.css">
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +      <div class="decor" aria-hidden="true">REC</div>
- Все буквы в тексте должны быть строчные для лучшего восприятия страницы машинами(поисковыми, скринридерами). Заглавное написание должно быть реализовано через CSS. В html можно сделать только первую букву фразы заглавной при желании, как в обычном приложении

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +      <p class="description title-decor">Что делать, когда не можешь делать ничего<br>Или почему нам так сложно
---

**Отлично:**

Это должен быть всего один параграф по смыслу. Так как на всех ширинах нам необходим перенос именно в этом месте, то тут как раз можно использовать тег ` <br>`, который практически не используется в современной верстке(кроме контактной информации и стихов)

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <h3 class="tittle-section">Почему сосредоточиться так сложно</h3>
- Уровень заголовка не соответствует структуре страницы. Это заголовок секции, по структуре заголовков будет  h2


---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +      <h4 class="tittle-cards title-decor">Многозадачность</h4>
- Уровень заголовка не соответствует структуре страницы. Тут  и далее в секции будут h3

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <h3 class="tittle-section">Что снижает концентрацию внимания?</h3>
- Уровень заголовка не соответствует структуре страницы. Это заголовок секции

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +      <h4 class="tittle-cards title-decor">Многозадачность</h4>
- Уровень заголовка не соответствует структуре страницы. Тут и далее в секции будут заголовки выше по структуре

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <h3 class="tittle-section">Как концентрироваться лучше, чем золотая рыбка (то есть дольше трёх секунд)</h3>
- Уровень заголовка не соответствует структуре страницы.

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <p class="description title-decor">5 простых (на самом деле не очень) советов</p>
Это должен быть заголовок, он озаглавливает следующие подразделы, будет  h3

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <h3 class="tittle-section">Как концентрироваться лучше, чем золотая рыбка (то есть дольше трёх секунд)</h3>
---

**Можно лучше:**

- Тут article можно было бы использовать для всей правой части секции, так как это по сути одна статья, начиная с следующего заголовка
- А для подразделов можно было использовать список, или тэги div

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <div class="card">
---

**Отлично:**

- Для улучшения семантики этого блока можно использовать тег `<article>` 

 - https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <h3 class="description title-decor">А можно в картинках?</h3>
- Уровень заголовка не соответствует структуре страницы. Это обычный заголовок секции

2023-12-03 21:35 UTC, Avaakum commented on index.html
> +    <div class="sunset"><img src="./images/sunset.png" alt="закат" class="gallery_image" loading="lazy"></div>
---

**Отлично:**

Есть атрибуты для отложенной загрузки изображений

2023-12-05 19:59 UTC, KsuyVas commented
Здравствуйте. Исправила критические замечания. Надеюсь, ничего не пропустила. Единственное, скролл у меня пропал сам... Предполагаю, что когда работала с медиазапросами, что-то ненужное ушло... Большое спасибо вам за подробное ревью.

2023-12-06 19:52 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_

- Комментарии в коде

- https://disk.yandex.ru/i/bGdLvt8k0YCTLg  это должны быть заголовки с жирным шрифтом
 - https://disk.yandex.ru/i/3CehpbqJD1jhPA у этих заголовков(именно у пяти, не включая сверху) не должно быть жирного шрифта на всех ширинах экрана(сейчас так и есть, просто напоминаю на всякий случай)

 - **при ширине экрана более 1440px  всё должно выглядеть так же как при 1440px, только с разным расстоянием от краёв экрана**. Максимальная ширина контента в стилях изначально задана как 1440px, её не нужно менять. При ширине страницы более 1440 должны прибавляться только края:
     -    https://disk.yandex.ru/i/lQI0TmwTXzalFA при ширине более 1024 текст должен заполнять всю ширину контента только с отступами между разделов

- При ширине экрана 375px  _не совпадает с макетом_:
   -  https://disk.yandex.ru/i/Hr5HyrY9vx0mKQ  выравнивание



---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2023-12-06 19:52 UTC, Avaakum commented on styles/style.css
> +.header__theme-menu-button {
- На **всех кнопках** должен быть эффект `cursor: pointer`

2023-12-06 19:52 UTC, Avaakum commented on index.html
> +      <p class="description title-decor">5 простых (на самом деле не очень) советов</p>
Это  должен быть заголовок h3 по структуре, он ниже чем тот который выше, но и выше, чем следующие

2023-12-06 19:52 UTC, Avaakum commented on index.html
> +        <h3 class="tittle-cards title-decor">Представьте небо и облака</h3>
- Уровень заголовка не соответствует структуре страницы. Тут и далее в секции будут h4

2023-12-07 19:47 UTC, KsuyVas commented
Спасибо!)

2023-12-07 19:48 UTC, merged